### PR TITLE
Update to aff 4

### PR DESCRIPTION
**Pull request by khanage**
Changed the order of the callbacks. Changed the FFI to use
EffFnAff instead of Aff directly.

Added a reference to purescript-aff-promise as Affs need to be run
to promises to pass them back into FFI land.

Tests run, and there's been a bit of manual testing as well.

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
Hey, sorry for taking so long to respond. Thanks a lot for all the work! Would you mind signing the CLA so I can get this merged?

**Comment by khanage** [comment]
Yeah no worries - I had to get approval at work for this which took a little while so I forgot to come back and do this :)

**Comment by kRITZCREEK** [comment]
So did you get the approval? It doesn't say you signed yet ^^

**Comment by khanage** [comment]
Sure did - looks like it didn't go through the first time I signed it. All good now ^^

**Comment by kRITZCREEK** [comment]
Thanks!

**Pull request merged**
